@echo off
REM (c) Microsoft Corporation. All rights reserved - Highly Confidential Material
REM /************************************************************************/
REM /* This script runs the GetValueSecure application.  It requires the    */
REM /* following parameters:                                                */
REM /*                                                                      */
REM /* Usage 1 (requires the MVS client certificates, MVSCA.der,            */
REM /* MVSClient.der and MVSClient.key, to be in the current directory):    */
REM /* -  the hostname/IP address of the MetaView Server                    */
REM /* -  the username                                                      */
REM /* -  the password                                                      */
REM /*                                                                      */
REM /* Usage 2 (requires security certificates generated by                 */
REM /* GenerateCertificates):                                               */
REM /* -  the hostname/IP address of the MetaView Server                    */
REM /* -  the Certificate Authority certificate filename                    */
REM /* -  the Client certificate filename                                   */
REM /* -  the Client private key filename                                   */
REM /*                                                                      */
REM /* For details of the script, see the comments in the source code.      */
REM /*                                                                      */
REM /* You will normally need to carry out these steps:                     */
REM /* -  generate certificates using GenerateCertificate                   */
REM /* -  move them to this directory if using Usage 1                      */
REM /* -  run this script; it will fail                                     */
REM /* -  use a client to find the new certificate in the OML tree (under   */
REM /*    MetaView Server / Security Certificates) and authorize it         */
REM /* -  run this script again; it should succeed                          */
REM /*                                                                      */
REM /* This application requires the IAIK security libraries (iaik_ssl.jar  */
REM /* and iaik_jce.jar), and Jacorb libraries to be present in the         */
REM /* ..\classes directory.                                                */
REM /* See http://jce.iaik.tugraz.at/, http://www.jacorb.org/, and the      */
REM /* readme.txt file.                                                     */
REM /************************************************************************/

@echo on
@java -classpath ..\classes;..\classes\*;..\classes\jacorb.jar;..\classes\jacorb-omgapi.jar;..\classes\jacorb-services.jar;..\classes\iaik_ssl.jar;..\classes\iaik_jce.jar;..\classes\slf4j-api.jar;..\classes\slf4j-jdk14.jar;..\classes\avalon-framework.jar;..\classes\jboss-rmi-api_1.0_spec.jar;..\classes\jacorbOverwriteSecurity.jar -Djava.util.logging.config.file=..\classes\logging.properties GetValueSecure %1 %2 %3 %4
