@echo off
REM (c) Microsoft Corporation. All rights reserved - Highly Confidential Material
REM /************************************************************************/
REM /* This script runs the QueryFields application.  It requires the       */
REM /* following parameters:                                                */
REM /*                                                                      */
REM /* Usage 1 (requires the MVS client certificates, MVSCA.der,            */
REM /* MVSClient.der and MVSClient.key, to be in the current directory):    */
REM /* -  the hostname/IP address of the MetaView Server                    */
REM /* -  the username                                                      */
REM /* -  the password                                                      */
REM /* -  the input filename                                                */
REM /* -  the output filename                                               */
REM /*                                                                      */
REM /* Usage 2 (requires security certificates generated by                 */
REM /* GenerateCertificates):                                               */
REM /* -  the hostname/IP address of the MetaView Server                    */
REM /* -  the Certificate Authority certificate filename                    */
REM /* -  the Client certificate filename                                   */
REM /* -  the Client private key filename                                   */
REM /* -  the input filename                                                */
REM /* -  the output filename                                               */
REM /*                                                                      */
REM /* For details of the script, see the comments in the source code.      */
REM /*                                                                      */
REM /* This application may require the IAIK security libraries,            */
REM /* iaik_ssl.jar and iaik_jce.jar, and Jacorb libraries to be present in */
REM /* the ..\classes directory.  See the readme.txt file for details.      */
REM /************************************************************************/

@echo on
@java -classpath ..\classes;..\classes\*;..\classes\jacorb.jar;..\classes\jacorb-omgapi.jar;..\classes\jacorb-services.jar;..\classes\iaik_ssl.jar;..\classes\iaik_jce.jar;..\classes\slf4j-api.jar;..\classes\slf4j-jdk14.jar;..\classes\avalon-framework.jar;..\classes\jboss-rmi-api_1.0_spec.jar;..\classes\jacorbOverwriteSecurity.jar -Djava.util.logging.config.file=..\classes\logging.properties QueryFields %1 %2 %3 %4 %5 %6
